-- MySQL Script generated by MySQL Workbench
-- Wed Oct 21 14:24:38 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';



-- -----------------------------------------------------
-- Table `global`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `global` ;

CREATE TABLE IF NOT EXISTS `global` (
  `global_password_min_length` INT NULL DEFAULT 8,
  `global_password_min_num` INT NULL DEFAULT 1,
  `global_password_min_upper` INT NULL DEFAULT 1,
  `global_password_min_lower` INT NULL DEFAULT 1,
  `global_password_min_special` INT NULL DEFAULT 0,
  `global_password_renew_days` INT NULL DEFAULT 0,
  `global_password_no_renew_within_hours` INT NULL DEFAULT 0,
  `global_password_maxattempts` INT NULL DEFAULT 6,
  `global_default_homepage` VARCHAR(100) NULL)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `user` ;

CREATE TABLE IF NOT EXISTS `user` (
  `iduser` INT NOT NULL AUTO_INCREMENT,
  `user_deleted` TINYINT NOT NULL DEFAULT 0,
  `user_createtime` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `user_disabled` TINYINT NULL DEFAULT 0,
  `user_username` VARCHAR(100) NOT NULL,
  `user_lastname` VARCHAR(100) NULL,
  `user_firstname` VARCHAR(100) NULL,
  `user_email` VARCHAR(256) NULL,
  `user_phone1` VARCHAR(21) NULL,
  `user_phone2` VARCHAR(21) NULL,
  `user_address1` VARCHAR(100) NULL,
  `user_address2` VARCHAR(100) NULL,
  `user_address3` VARCHAR(100) NULL,
  `user_address4` VARCHAR(100) NULL,
  `user_city` VARCHAR(60) NULL,
  `user_postcode` VARCHAR(10) NULL,
  `user_country` VARCHAR(60) NULL,
  `user_timezone` VARCHAR(45) NULL,
  `user_x509_serial` VARCHAR(45) NULL,
  `user_apikey` VARCHAR(64) NULL,
  `user_forcereset` TINYINT NULL DEFAULT 1,
  `user_expires` DATETIME NULL,
  `user_hash` VARCHAR(64) NULL,
  `user_salt` VARCHAR(64) NULL,
  `user_prev_hash` VARCHAR(1600) NULL,
  `user_prev_salt` VARCHAR(1600) NULL,
  `user_pw_renew_date` DATETIME NULL,
  `user_pw_change_date` DATETIME NULL,
  `user_security` INT NULL DEFAULT 0,
  `user_last_signin` DATETIME NULL,
  `user_disable_timestamp` DATETIME NULL,
  `user_failed_login_count` INT NULL,
  `user_default_page` VARCHAR(100) NULL,
  PRIMARY KEY (`iduser`, `user_deleted`),
  UNIQUE INDEX `user_username_UNIQUE` (`user_username` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rolling`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `rolling` ;

CREATE TABLE IF NOT EXISTS `rolling` (
  `rolling_entity` VARCHAR(45) NOT NULL,
  `rolling_entity_disabled` TINYINT(1) NULL,
  `rolling_modulus` INT NULL DEFAULT 10,
  `rolling_counters` VARCHAR(500) NULL,
  `rolling_idx` INT NULL,
  `rolling_target` DOUBLE NULL,
  `rolling_disable_seconds` INT NULL,
  `rolling_disable_timestamp` DATETIME NULL,
  UNIQUE INDEX `rolling_entity_UNIQUE` (`rolling_entity` ASC),
  PRIMARY KEY (`rolling_entity`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `audit`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `audit` ;

CREATE TABLE IF NOT EXISTS `audit` (
  `audit_timestamp` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `audit_type` VARCHAR(20) NULL,
  `audit_user` INT NULL,
  `audit_description` VARCHAR(200) NULL,
  `audit_ipaddress` VARCHAR(60) NULL,
  PRIMARY KEY (`audit_timestamp`),
  INDEX `type` (`audit_type` ASC, `audit_timestamp` ASC),
  INDEX `user` (`audit_user` ASC, `audit_timestamp` ASC),
  CONSTRAINT `fk_audit_user`
    FOREIGN KEY (`audit_user`)
    REFERENCES `user` (`iduser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
