-- MySQL Script generated by MySQL Workbench
-- Sun Mar  7 17:00:16 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema stock
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema stock
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `stock` DEFAULT CHARACTER SET utf8 ;
USE `stock` ;

-- -----------------------------------------------------
-- Table `stock`.`stock`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `stock`.`stock` ;

CREATE TABLE IF NOT EXISTS `stock`.`stock` (
  `idstock` INT NOT NULL AUTO_INCREMENT,
  `stock_code` VARCHAR(5) NULL,
  `stock_name` VARCHAR(45) NULL,
  PRIMARY KEY (`idstock`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `stock`.`record`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `stock`.`record` ;

CREATE TABLE IF NOT EXISTS `stock`.`record` (
  `record_timestamp` DATETIME NOT NULL,
  `record_stock` INT NOT NULL,
  `record_value` DOUBLE NULL,
  PRIMARY KEY (`record_timestamp`, `record_stock`),
  INDEX `fk_record_stock_idx` (`record_stock` ASC),
  CONSTRAINT `fk_record_stock`
    FOREIGN KEY (`record_stock`)
    REFERENCES `stock`.`stock` (`idstock`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `stock`.`portfolio`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `stock`.`portfolio` ;

CREATE TABLE IF NOT EXISTS `stock`.`portfolio` (
  `idportfolio` INT NOT NULL AUTO_INCREMENT,
  `portfolio_stock` INT NOT NULL,
  `portfolio_timestamp` DATETIME NOT NULL,
  `portfolio_buysell` ENUM('buy', 'sell') NULL,
  `portfolio_price` DOUBLE NULL,
  `portfolio_qty` DOUBLE NULL,
  `portfolio_currency` VARCHAR(4) NULL,
  PRIMARY KEY (`idportfolio`, `portfolio_stock`, `portfolio_timestamp`),
  INDEX `fk_portfolio_stock1_idx` (`portfolio_stock` ASC),
  CONSTRAINT `fk_portfolio_stock1`
    FOREIGN KEY (`portfolio_stock`)
    REFERENCES `stock`.`stock` (`idstock`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `stock`.`watch`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `stock`.`watch` ;

CREATE TABLE IF NOT EXISTS `stock`.`watch` (
  `idwatch` INT NOT NULL AUTO_INCREMENT,
  `watch_stock` INT NOT NULL,
  `watch_once` TINYINT NULL DEFAULT 1,
  `watch_done` TINYINT NOT NULL DEFAULT 0,
  `watch_below` DOUBLE NULL DEFAULT 0.0,
  `watch_below_triggered` TINYINT NULL DEFAULT 0,
  `watch_above` DOUBLE NULL DEFAULT 0.0,
  `watch_above_triggered` TINYINT NULL DEFAULT 0,
  PRIMARY KEY (`idwatch`, `watch_stock`, `watch_done`),
  INDEX `fk_watch_stock1_idx` (`watch_stock` ASC),
  INDEX `index3` (`watch_stock` ASC, `watch_done` ASC),
  CONSTRAINT `fk_watch_stock1`
    FOREIGN KEY (`watch_stock`)
    REFERENCES `stock`.`stock` (`idstock`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `stock`.`target`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `stock`.`target` ;

CREATE TABLE IF NOT EXISTS `stock`.`target` (
  `idtarget` INT NOT NULL AUTO_INCREMENT,
  `target_stock` INT NOT NULL,
  `target_sell_percent` DOUBLE NULL,
  `target_sell_price` DOUBLE NULL,
  `target_buy_price` VARCHAR(45) NULL,
  PRIMARY KEY (`idtarget`, `target_stock`),
  INDEX `fk_target_stock1_idx` (`target_stock` ASC),
  CONSTRAINT `fk_target_stock1`
    FOREIGN KEY (`target_stock`)
    REFERENCES `stock`.`stock` (`idstock`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
