-- MySQL Script generated by MySQL Workbench
-- Wed Mar 24 17:36:33 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema stock
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema stock
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `stock` DEFAULT CHARACTER SET utf8 ;
USE `stock` ;

-- -----------------------------------------------------
-- Table `stock`.`stock`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `stock`.`stock` ;

CREATE TABLE IF NOT EXISTS `stock`.`stock` (
  `idstock` INT NOT NULL AUTO_INCREMENT,
  `stock_code` VARCHAR(5) NULL,
  `stock_name` VARCHAR(45) NULL,
  `stock_international_code` VARCHAR(45) NULL,
  `stock_margin` DOUBLE NULL,
  PRIMARY KEY (`idstock`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `stock`.`record`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `stock`.`record` ;

CREATE TABLE IF NOT EXISTS `stock`.`record` (
  `record_timestamp` DATETIME NOT NULL,
  `record_stock` INT NOT NULL,
  `record_value` DOUBLE NULL,
  `record_currency` VARCHAR(10) NULL,
  PRIMARY KEY (`record_timestamp`, `record_stock`),
  INDEX `fk_record_stock_idx` (`record_stock` ASC),
  CONSTRAINT `fk_record_stock`
    FOREIGN KEY (`record_stock`)
    REFERENCES `stock`.`stock` (`idstock`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `stock`.`portfolio`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `stock`.`portfolio` ;

CREATE TABLE IF NOT EXISTS `stock`.`portfolio` (
  `idportfolio` INT NOT NULL AUTO_INCREMENT,
  `portfolio_user` INT NOT NULL,
  `portfolio_stock` INT NOT NULL,
  `portfolio_timestamp` DATETIME NOT NULL,
  `portfolio_buysell` ENUM('buy', 'sell', 'div') NULL,
  `portfolio_price` DOUBLE NULL,
  `portfolio_qty` DOUBLE NULL,
  `portfolio_currency` VARCHAR(4) NULL,
  `portfolio_archive` TINYINT NULL DEFAULT 0,
  `portfolio_fees` DOUBLE NULL,
  `portfolio_fees_unit` VARCHAR(45) NULL,
  PRIMARY KEY (`idportfolio`, `portfolio_stock`, `portfolio_timestamp`, `portfolio_user`),
  INDEX `fk_portfolio_stock1_idx` (`portfolio_stock` ASC),
  CONSTRAINT `fk_portfolio_stock1`
    FOREIGN KEY (`portfolio_stock`)
    REFERENCES `stock`.`stock` (`idstock`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `stock`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `stock`.`user` ;

CREATE TABLE IF NOT EXISTS `stock`.`user` (
  `iduser` INT NOT NULL AUTO_INCREMENT,
  `user_deleted` TINYINT NOT NULL DEFAULT 0,
  `user_createtime` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `user_disabled` TINYINT NULL DEFAULT 0,
  `user_username` VARCHAR(100) NOT NULL,
  `user_lastname` VARCHAR(100) NULL DEFAULT NULL,
  `user_firstname` VARCHAR(100) NULL DEFAULT NULL,
  `user_email` VARCHAR(256) NULL DEFAULT NULL,
  `user_phone1` VARCHAR(21) NULL DEFAULT NULL,
  `user_phone2` VARCHAR(21) NULL DEFAULT NULL,
  `user_address1` VARCHAR(100) NULL DEFAULT NULL,
  `user_address2` VARCHAR(100) NULL DEFAULT NULL,
  `user_address3` VARCHAR(100) NULL DEFAULT NULL,
  `user_address4` VARCHAR(100) NULL DEFAULT NULL,
  `user_city` VARCHAR(60) NULL DEFAULT NULL,
  `user_postcode` VARCHAR(10) NULL DEFAULT NULL,
  `user_country` VARCHAR(60) NULL DEFAULT NULL,
  `user_timezone` VARCHAR(45) NULL DEFAULT NULL,
  `user_x509_serial` VARCHAR(45) NULL DEFAULT NULL,
  `user_apikey` VARCHAR(64) NULL DEFAULT NULL,
  `user_forcereset` TINYINT NULL DEFAULT 1,
  `user_expires` DATETIME NULL DEFAULT NULL,
  `user_hash` VARCHAR(64) NULL DEFAULT NULL,
  `user_salt` VARCHAR(64) NULL DEFAULT NULL,
  `user_prev_hash` VARCHAR(1600) NULL DEFAULT NULL,
  `user_prev_salt` VARCHAR(1600) NULL DEFAULT NULL,
  `user_pw_renew_date` DATETIME NULL DEFAULT NULL,
  `user_pw_change_date` DATETIME NULL DEFAULT NULL,
  `user_security` INT NULL DEFAULT 0,
  `user_last_signin` DATETIME NULL DEFAULT NULL,
  `user_disable_timestamp` DATETIME NULL DEFAULT NULL,
  `user_failed_login_count` INT NULL DEFAULT NULL,
  `user_default_page` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`iduser`, `user_deleted`),
  UNIQUE INDEX `user_username_UNIQUE` (`user_username` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `stock`.`watch`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `stock`.`watch` ;

CREATE TABLE IF NOT EXISTS `stock`.`watch` (
  `idwatch` INT NOT NULL AUTO_INCREMENT,
  `watch_user` INT NOT NULL,
  `watch_stock` INT NOT NULL,
  `watch_once` TINYINT NULL DEFAULT 1,
  `watch_done` TINYINT NULL DEFAULT 0,
  `watch_below` DOUBLE NULL DEFAULT 0.0,
  `watch_below_triggered` TINYINT NULL DEFAULT 0,
  `watch_above` DOUBLE NULL DEFAULT 0.0,
  `watch_above_triggered` TINYINT NULL DEFAULT 0,
  `watch_rti` DOUBLE NULL DEFAULT 0.0,
  PRIMARY KEY (`idwatch`, `watch_stock`, `watch_user`),
  INDEX `fk_watch_stock1_idx` (`watch_stock` ASC),
  INDEX `index3` (`watch_stock` ASC, `watch_done` ASC),
  INDEX `fk_watch_user1_idx` (`watch_user` ASC),
  CONSTRAINT `fk_watch_stock1`
    FOREIGN KEY (`watch_stock`)
    REFERENCES `stock`.`stock` (`idstock`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_watch_user1`
    FOREIGN KEY (`watch_user`)
    REFERENCES `stock`.`user` (`iduser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `stock`.`target`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `stock`.`target` ;

CREATE TABLE IF NOT EXISTS `stock`.`target` (
  `idtarget` INT NOT NULL AUTO_INCREMENT,
  `target_stock` INT NOT NULL,
  `target_sell_percent` DOUBLE NULL,
  `target_sell_price` DOUBLE NULL,
  `target_buy_price` VARCHAR(45) NULL,
  PRIMARY KEY (`idtarget`, `target_stock`),
  INDEX `fk_target_stock1_idx` (`target_stock` ASC),
  CONSTRAINT `fk_target_stock1`
    FOREIGN KEY (`target_stock`)
    REFERENCES `stock`.`stock` (`idstock`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `stock`.`global`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `stock`.`global` ;

CREATE TABLE IF NOT EXISTS `stock`.`global` (
  `global_password_min_length` INT NULL DEFAULT 8,
  `global_password_min_num` INT NULL DEFAULT 1,
  `global_password_min_upper` INT NULL DEFAULT 1,
  `global_password_min_lower` INT NULL DEFAULT 1,
  `global_password_min_special` INT NULL DEFAULT 0,
  `global_password_renew_days` INT NULL DEFAULT 0,
  `global_password_no_renew_within_hours` INT NULL DEFAULT 0,
  `global_password_maxattempts` INT NULL DEFAULT 6,
  `global_default_homepage` VARCHAR(100) NULL DEFAULT NULL)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `stock`.`rolling`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `stock`.`rolling` ;

CREATE TABLE IF NOT EXISTS `stock`.`rolling` (
  `rolling_entity` VARCHAR(45) NOT NULL,
  `rolling_entity_disabled` TINYINT(1) NULL DEFAULT NULL,
  `rolling_modulus` INT NULL DEFAULT 10,
  `rolling_counters` VARCHAR(500) NULL DEFAULT NULL,
  `rolling_idx` INT NULL DEFAULT NULL,
  `rolling_target` DOUBLE NULL DEFAULT NULL,
  `rolling_disable_seconds` INT NULL DEFAULT NULL,
  `rolling_disable_timestamp` DATETIME NULL DEFAULT NULL,
  UNIQUE INDEX `rolling_entity_UNIQUE` (`rolling_entity` ASC),
  PRIMARY KEY (`rolling_entity`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `stock`.`audit`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `stock`.`audit` ;

CREATE TABLE IF NOT EXISTS `stock`.`audit` (
  `audit_timestamp` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `audit_type` VARCHAR(20) NULL DEFAULT NULL,
  `audit_user` INT NULL DEFAULT NULL,
  `audit_description` VARCHAR(200) NULL DEFAULT NULL,
  `audit_ipaddress` VARCHAR(60) NULL DEFAULT NULL,
  PRIMARY KEY (`audit_timestamp`),
  INDEX `type` (`audit_type` ASC, `audit_timestamp` ASC),
  INDEX `user` (`audit_user` ASC, `audit_timestamp` ASC),
  CONSTRAINT `fk_audit_user`
    FOREIGN KEY (`audit_user`)
    REFERENCES `stock`.`user` (`iduser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
